### PR TITLE
Fix for Obsidian 1.6.x compatibility

### PR DESCRIPTION
**Pull request by Acylation**
Will merge and release this after 1.6.x becomes public. Before that we will have a nightly build that need to install manually for Obsidian insiders.

### CODE REVIEW

**Comment by Acylation** [comment]
It's expected to work on previous versions of Obsidian after merging this. The only problem is we changed the icon for `open in new window`. So I think it's fine to keep the minAppVersion.

**Comment by GitMurf** [comment]
> Will merge and release this after 1.6.x becomes public. Before that we will have a nightly build that need to install manually for Obsidian insiders.

@Acylation / @marcusolsson have you considered using BRAT for delivery of nightly builds / beta testing? It is super easy to setup and a big part of Obsidian ecosystem is using it these days to test plugins and deliver beta versions etc.

Here are details: https://tfthacker.com/brat-developers#manifest-beta.json

**Comment by marcusolsson** [comment]
@GitMurf Love BRAT! Didn't know about the manifest-beta.json file though. I've added it to the CI now, so every merged PR will create a beta release now. Let me know if it doesn't work 🙏

**Comment by GitMurf** [comment]
@marcusolsson worked like a charm. Nice work and thank you!

**Comment by Acylation** [comment]
Merge upon Obsidian 1.6.2 becomes public.

**Pull request merged**
