### PR TITLE
Gallery: Configurable image fitting style

### PR DESCRIPTION
**Pull request by Acylation**
A solution to #224

Effect:
image

### CODE REVIEW

**Comment by marcusolsson** [comment]
Like I mentioned in the issue, I think this should be configurable, since both are reasonable settings.

**Comment by Acylation** [comment]
Got it, I will give it a try.

**Comment by Acylation** [comment]
Ready for review now @marcusolsson

**Review by marcusolsson — CHANGES_REQUESTED** [review]
Much better! My main concern is that the plugin isn't using a "switch button" anywhere else so this is introducing a new UX pattern.

I'm personally not a fan of the toggle buttons, since the current value can be confusing. For example, does the button label show the current setting, or the setting that you get if you click it?

I'd suggest that we either:

- Use a dropdown with the two values

CleanShot 2022-12-11 at 22 58 20@2x

- Use a switch component that favors one of the values

CleanShot 2022-12-11 at 23 00 07@2x

Also, I think we use use "Fit and Fill" rather than "Fit and Crop" ([first](https://www.bannerbear.com/help/articles/26-difference-between-fit-and-fill/) and [second](https://support.beautiful.ai/hc/en-us/articles/360018488832-Image-Aspect-Ratio-Fit-vs-Fill-) reference).

**Comment by Acylation** [comment]
Yeah, the toggle buttons are really confusing. I chose this design because it displays the styles well and has the shortest way to reach. But the backoff, just like you commented, it's not native.

Between the drop-down and switch bar, I prefer the former. A problem with the switch bar is, it has a preference naturally. If there's an inline way to mute the switch bar when the corresponding value is true,  I would apply it.

**Review by marcusolsson — APPROVED** [review]
Solid work on this! 💪  Thank you!

**Pull request merged**
